services:
  postgres-db:
    image: postgres:16-bookworm
    container_name: taskflow-db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - TZ=America/Buenos_Aires
    ports:
      - "5432:5432"
    volumes:
      - taskflow-db-data:/var/lib/postgresql/data

volumes:
  taskflow-db-data: